[package]
name = "brain"
version = "0.1.0"
description = "Artificial Brain - a 3D second brain"
authors = ["Pavvy"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "brain_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde_yaml = "0.9.34"
chrono = { version = "0.4.45", default-features = false, features = ["clock"] }
ulid = "3.0.0"
notify-debouncer-mini = "0.7.0"
tauri-plugin-dialog = "2.7.3"
tauri-plugin-global-shortcut = "2.3.2"
tauri-plugin-single-instance = "2.4.5"
scraper = "0.27.0"
url = "2.5.8"
reqwest = { version = "0.13.5", features = ["gzip", "json"] }


# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
